title: John Rodriguez Live # your site title
author: johnrlive
email: your-email@domain.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
#url: "http://localhost:3000" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://agitated-goldwasser-8721d4.netlify.com/"
twitter_username: johnrlive # replace with your_twitter_username or comment to remove link from footer
github_username:  johnrlive # replace with your_github_username or comment to remove link from footer
instagram_username: nerdlifejohn # replace with your_instagram_username or comment to remove link from footer
social:
  name: John Rodriguez
  links:
    - https://twitter.com/johnrlive
    - https://www.facebook.com/johnrlive
    - https://www.linkedin.com/in/johnrlive
    - https://plus.google.com/+johnrlive
    - https://github.com/johnrlive
    - https://keybase.io/johrnlive

disqus:
  shortname: johnrlive # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

#plugins:
#  - jekyll-sitemap
#  - jekyll-seo-tag
